Repository GEOS-ESM/GMAOpyobs, pull requests merged in 2024-08, with the labels that each got.

#51 Normalizing the moments of the phase function
  CHANGELOG.md
  src/pyobs/aop.py
Labels: bug

#49 Feature/#48/acollow/pm
  CHANGELOG.md
  src/pyobs/aop.py
  src/pyobs/mietable.py
Labels: enhancement

#57 PM2.5 Calculation in Differing GEOS Configurations
  CHANGELOG.md
  src/config/g2g_pm25.yaml
  src/config/geos529_pm25.yaml
  src/config/m2_pm25.yaml
  src/pyobs/aop.py
Labels: Non 0-diff
